import { Composition, registerRoot, type CalculateMetadataFunction } from "remotion";
import { Renderer, type TimelineSpec } from "@json-render/remotion";
import { SHARE_TIMELINE_COMPOSITION_ID } from "@/lib/media/remotion-shared";

type ShareTimelineProps = {
  spec: TimelineSpec;
};

const fallbackSpec: TimelineSpec = {
  composition: {
    id: SHARE_TIMELINE_COMPOSITION_ID,
    fps: 30,
    width: 1080,
    height: 1920,
    durationInFrames: 90,
  },
  tracks: [
    {
      id: "main",
      name: "Main",
      type: "video",
      enabled: true,
    },
  ],
  clips: [
    {
      id: "fallback-clip",
      trackId: "main",
      component: "TitleCard",
      props: {
        title: "Share Video",
        subtitle: "Generated by json-render",
      },
      from: 0,
      durationInFrames: 90,
      transitionIn: {
        type: "fade",
        durationInFrames: 10,
      },
      transitionOut: {
        type: "fade",
        durationInFrames: 10,
      },
    },
  ],
  audio: {
    tracks: [],
  },
};

const fallbackComposition = {
  fps: 30,
  width: 1080,
  height: 1920,
  durationInFrames: 90,
};

const ShareTimelineComposition = ({ spec }: ShareTimelineProps) => {
  return <Renderer spec={spec} />;
};

const calculateMetadata: CalculateMetadataFunction<ShareTimelineProps> = async ({ props }) => {
  const spec = props?.spec ?? fallbackSpec;
  const composition = spec.composition ?? fallbackComposition;

  return {
    fps: Math.max(1, Math.round(composition.fps || fallbackComposition.fps)),
    width: Math.max(64, Math.round(composition.width || fallbackComposition.width)),
    height: Math.max(64, Math.round(composition.height || fallbackComposition.height)),
    durationInFrames: Math.max(
      1,
      Math.round(composition.durationInFrames || fallbackComposition.durationInFrames)
    ),
  };
};

export const RemotionShareRoot = () => {
  return (
    <Composition
      id={SHARE_TIMELINE_COMPOSITION_ID}
      component={ShareTimelineComposition}
      fps={fallbackComposition.fps}
      width={fallbackComposition.width}
      height={fallbackComposition.height}
      durationInFrames={fallbackComposition.durationInFrames}
      defaultProps={{ spec: fallbackSpec }}
      calculateMetadata={calculateMetadata}
    />
  );
};

registerRoot(RemotionShareRoot);
